Update TrackNamespaceManager
nttcom/moq-wasm pull request #103
Opened 2024-10-07 14:05 UTC by tetter27

### Changes
- Name changed: `TrackNamespaceManager` -> `PubSubRelationManager`
- Refactored the folder structure and the model for pubsub management
- Supported Subscribe ID and Track Alias (Relay side only)
- Changed processes around PubSubRelationManager in message handlers
- Fulfilled almost all processes in new functions with unit tests.

### TODO
- Support Subscribe ID and Track Alias in client sides (will handle at next PR)
- Names of PubSubRelationCommands are too long (will make Issue)
- Redundant in the flow of processing in unit tests (will make Issue)
- Error handlings in PubSubRelationManager is incomplete (will handle when Termination Error Code supported)

2024-10-09 11:14 UTC, yuki-uchida requested changes

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/messages/control_messages/subscribe.rs
> +    pub fn replace_subscribe_id_and_track_alias(&mut self, subscribe_id: u64, track_alias: u64) {
Wouldn't it be clearer to execute the individual functions twice?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
> +    pub fn replace_subscribe_id(&mut self, subscribe_id: u64) {
I think `set_` is more enginneer friendly.

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
> +        buf.extend(u8::from(self.group_order).to_be_bytes());
Do we need a write function for u8?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes.rs
> +pub mod consumer_node;
Please change direcotry names
modules > subscription_models > nodes > consumer_node.rs
to
modules > models > subscription > nodes > consumer.rs / producer.rs

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +                    == (track_namespace.clone(), track_name.clone())
Does track_name need to be clone?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/subscriptions.rs
> +    subscription_status: Status,
I think the name “status” is sufficient.

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +        let activate = subscription.activate();
I think `is_activate` would be better

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_within_max_subscribe_id(&self, subscribe_id: SubscribeId) -> bool {
How about the following function names?
- `can_create_subscription`
- `is_subscription_limit_reached`
- `has_subscription_capacity`
- `is_within_subscription_limit`

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_subscribe_id_unique(&self, subscribe_id: SubscribeId) -> bool {
How about the following function names?
- `is_subscribed`
- `is_subscription_exists`
- `has_duplicate_subscription`
- `has_duplicate_subscribe_id`
- `is_valid_subscribe_id`

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_track_alias_unique(&self, track_alias: TrackAlias) -> bool {
How about the following function names?
- `is_valid_track_alias`
- `validate_track_alias`
- `has_duplicate_track_alias`

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn find_unused_subscribe_id_and_track_alias(&self) -> Result<(SubscribeId, TrackAlias)> {
Is this function used? And is it necessary?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/producer_node.rs
> +    pub(crate) struct SubscriptionUtils {
Why is it  defining a new structure called SubscriptionUtils instead of using Subscription?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-core/src/modules/subscription_models/nodes/producer_node.rs
> +        pub(crate) fn normal_variable(subscribe_id: u64) -> Self {
I think `createSubscriptionUtils` is better

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/control_message_handler.rs
> +pub(crate) mod test_utils {
Why do you think `test_utils` is more appropriate?
What about `test_setup`?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/pubsub_relation_manager/commands.rs
> +    RegisterPubSubRelation {
Why is Register used instead of Set?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_handler.rs
> +        .is_valid_subscriber_subscribe_id(subscribe_message.subscribe_id(), client.id)
Maybe method tame is room to make better.

- `has_subscription_capacity()` 
- `isin_subscription_limit`
- `is_subscription_limit_reached`

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_handler.rs
> +        .get_publisher_subscription_by_full_track_name(
How about `get_upstream_subscription_by_full_track_name`?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_handler.rs
> +async fn set_only_subscriber_subscription(
I don't understand why `set_subscription` is not used, and I don't understand what “only” indicates.

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_handler.rs
> +            track_name.clone(),
Why `.clone()` is needed?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_ok_handler.rs
> +    let ids = pubsub_relation_manager_repository
I think it would be better to leave subscriber_session_ids as it is.

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/pubsub_relation_manager/interface.rs
> +    async fn activate_subscriber_subscription(
Subscriber has two meanings, one for server subscriber subscriptions and the other for client subscriber subscriptions, so a more descriptive name is necessary.

How about use `upstream` or `downstream`?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/handlers/subscribe_ok_handler.rs
> +            .set_publisher_announced_namespace(track_namespace.clone(), publisher_session_id)
How about set_upstream_announced_namaspace?

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/pubsub_relation_manager/commands.rs
Please change direcotry.
modules > pubsub_relation_manager > manager.rs
modules > managers > pubsub_relation_manager > manager.rs

2024-10-09 11:14 UTC, yuki-uchida commented on moqt-server/src/modules/pubsub_relation_manager/interface.rs
How about calling it a wrapper.rs?
I think it is more of a wrapping element than an interface.

Also, it doesn't have to be a Trait. It would be enough to have a simple wrapper function with a manager as an argument.

2024-10-10 00:15 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +                    == (track_namespace.clone(), track_name.clone())
TODO:
track_namespace: Vec<&str>
track_name: &str

2024-10-10 00:22 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_within_max_subscribe_id(&self, subscribe_id: SubscribeId) -> bool {
merge with `is_subscribe_id_unique`

2024-10-10 00:44 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn find_unused_subscribe_id_and_track_alias(&self) -> Result<(SubscribeId, TrackAlias)> {
rename `create_valid_subscribe_id_and_track_alias`

2024-10-10 01:09 UTC, tetter27 commented on moqt-server/src/modules/control_message_handler.rs
> +pub(crate) mod test_utils {
use `test_helper_fn`

2024-10-10 01:17 UTC, tetter27 commented on moqt-server/src/modules/handlers/subscribe_handler.rs
> +            track_name.clone(),
TODO:
ban all clone()

2024-10-10 01:18 UTC, tetter27 commented on moqt-server/src/modules/handlers/subscribe_ok_handler.rs
> +    let ids = pubsub_relation_manager_repository
use `id_and_alias`

2024-10-10 01:30 UTC, tetter27 commented on moqt-server/src/modules/pubsub_relation_manager/interface.rs
changed `wrapper.rs`.

TODO:
Reconsider the configuration around Trait

2024-10-10 03:54 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_subscribe_id_unique(&self, subscribe_id: SubscribeId) -> bool {
merged with `is_within_max_subscribe_id`

2024-10-10 03:55 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/consumer_node.rs
> +    fn is_track_alias_unique(&self, track_alias: TrackAlias) -> bool {
renamed to `is_track_alias_valid`

2024-10-10 04:15 UTC, tetter27 commented on moqt-core/src/modules/subscription_models/nodes/producer_node.rs
> +        pub(crate) fn normal_variable(subscribe_id: u64) -> Self {
renamed to `SubscriptionVariables` and `common_subscription_variable`

2024-10-10 06:27 UTC, yuki-uchida approved these changes

2024-10-10 06:28 UTC, merged